# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  name "grove"
  desc "Manage CoW-cloned workspaces with warm build caches"
  homepage "https://github.com/chrisbanes/grove"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grove"

  on_macos do
    on_intel do
      url "https://github.com/chrisbanes/grove/releases/download/v#{version}/grove_#{version}_darwin_amd64.tar.gz"
      sha256 "e23ae37d95e34223a88ba10eae8996b54a2da6737374ebc82dd667d334b9c5ae"
    end
    on_arm do
      url "https://github.com/chrisbanes/grove/releases/download/v#{version}/grove_#{version}_darwin_arm64.tar.gz"
      sha256 "2b328a73ad3c486d9ac997e6f892652d02e9413cd74824ea4914f1b3e3fdc2ff"
    end
  end

  # No zap stanza required
end
