# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  name "grove"
  desc "Manage CoW-cloned workspaces with warm build caches"
  homepage "https://github.com/chrisbanes/grove"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grove"
  depends_on formula: [
      "rsync",
    ]

  on_macos do
    on_intel do
      url "https://github.com/chrisbanes/grove/releases/download/v#{version}/grove_#{version}_darwin_amd64.tar.gz"
      sha256 "a7efb1d671b92d118f17375beeadee06bd6dd432fc068fd9d810fe9314849e00"
    end
    on_arm do
      url "https://github.com/chrisbanes/grove/releases/download/v#{version}/grove_#{version}_darwin_arm64.tar.gz"
      sha256 "f2b0fbccf596ee575d612a29262d246ce3f1b10bf7500c7ef6ad73f2e2f9be19"
    end
  end

  # No zap stanza required
end
